services:
  client:
    container_name: client
    build:
      context: ./app/client
    ports:
      - "8080:80"
    depends_on:
      - server
    volumes:
      - ./images/:/static/images
    networks:
      - my_network

  server:
    container_name: server
    build:
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./images/:/server/images
    networks:
      - my_network
    restart: always

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB = admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d admin -U admin" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge